name: Code Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    # 3. Install dependencies
    - name: Install dependencies
      run: npm ci

    # 4. Run tests with coverage
    - name: Run tests with coverage
      run: npm run test:coverage-ci

    # 5. Upload coverage folder as artifact
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage
        retention-days: 7
      if: always()  # Always upload coverage even if tests fail

    # 6. Generate coverage summary
    - name: Coverage Summary
      run: |
        if [ -f coverage/lcov-report/index.html ]; then
          echo "✅ Coverage report generated successfully"
          echo "📊 Check the uploaded artifact for detailed coverage report"
        else
          echo "⚠️ Coverage report not found"
        fi
      if: always()

    # 7. Optional: Comment PR with coverage info (requires lcov.info)
    - name: Coverage Comment
      uses: romeovs/lcov-reporter-action@v0.3.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info
        delete-old-comments: true
      if: github.event_name == 'pull_request' && hashFiles('coverage/lcov.info') != ''
      continue-on-error: true